// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/has1985/myapp/myapp/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_ed453a2cae7ad049, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
}

func init() {
	proto.RegisterFile("github.com/has1985/myapp/myapp/pkg/pb/service.proto", fileDescriptor_ed453a2cae7ad049)
}

var fileDescriptor_ed453a2cae7ad049 = []byte{
	// 292 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0xcd, 0x4a, 0x3b, 0x31,
	0x14, 0xc5, 0xe9, 0x1f, 0xfe, 0x56, 0xb3, 0x51, 0x66, 0x21, 0xa5, 0xba, 0x90, 0xae, 0x8a, 0xda,
	0x04, 0x2d, 0x82, 0x1f, 0x2b, 0x05, 0x71, 0x25, 0x48, 0x17, 0x82, 0xee, 0x92, 0xf1, 0x36, 0x0d,
	0xce, 0xe4, 0x5e, 0x92, 0x74, 0xec, 0x6c, 0x7d, 0x05, 0x1f, 0xcd, 0x57, 0xf0, 0x41, 0x64, 0x66,
	0x32, 0x32, 0xa8, 0x0b, 0x37, 0x21, 0xe7, 0x7e, 0x9c, 0x1f, 0x9c, 0xcb, 0xa6, 0xda, 0x84, 0xc5,
	0x52, 0xf1, 0x14, 0x73, 0xb1, 0x90, 0xfe, 0xe8, 0xec, 0xf4, 0x44, 0xe4, 0xa5, 0x24, 0x8a, 0x2f,
	0x3d, 0x6b, 0x41, 0x4a, 0x78, 0x70, 0x85, 0x49, 0x81, 0x93, 0xc3, 0x80, 0x49, 0x3f, 0xca, 0xe1,
	0x8e, 0x46, 0xd4, 0x19, 0x88, 0xba, 0xac, 0x96, 0x73, 0x01, 0x39, 0x85, 0xb2, 0x99, 0x1a, 0xee,
	0xc6, 0xa6, 0x24, 0x23, 0xa4, 0xb5, 0x18, 0x64, 0x30, 0x68, 0x7d, 0xec, 0x5e, 0x76, 0xc0, 0x60,
	0x0b, 0x2c, 0xc9, 0xe1, 0xaa, 0x6c, 0x9c, 0xd2, 0x89, 0x06, 0x3b, 0x29, 0x64, 0x66, 0x9e, 0x64,
	0x00, 0xf1, 0xe3, 0x13, 0x2d, 0x0e, 0x3b, 0xc3, 0xfe, 0x45, 0x6a, 0x0d, 0x4e, 0x20, 0xd5, 0x90,
	0x5f, 0x80, 0xe7, 0x1d, 0xa0, 0xb1, 0x73, 0x54, 0x19, 0xae, 0x90, 0xc0, 0x76, 0x91, 0x1a, 0x5d,
	0xfe, 0x65, 0x51, 0x89, 0x66, 0x77, 0x74, 0xc0, 0x36, 0xef, 0xc1, 0x79, 0x83, 0x76, 0x06, 0x9e,
	0xd0, 0x7a, 0x48, 0x06, 0xac, 0x5f, 0x34, 0xa5, 0x41, 0x6f, 0xaf, 0x37, 0xde, 0x98, 0xb5, 0xf2,
	0xf8, 0x81, 0xfd, 0xbf, 0xad, 0xb2, 0x4b, 0xee, 0x18, 0xbb, 0x81, 0x10, 0x17, 0x93, 0x6d, 0xde,
	0xe4, 0xc1, 0xdb, 0xb0, 0xf8, 0x75, 0x15, 0xd6, 0x70, 0xc0, 0xdb, 0x70, 0xbf, 0x21, 0x46, 0x5b,
	0xaf, 0xef, 0x1f, 0x6f, 0xff, 0x58, 0xb2, 0x2e, 0xa2, 0xf5, 0xd5, 0xfe, 0xe3, 0xf8, 0x4f, 0xf7,
	0xba, 0x20, 0xa5, 0xd6, 0x6a, 0xce, 0xf4, 0x33, 0x00, 0x00, 0xff, 0xff, 0x1d, 0x66, 0x51, 0x99,
	0xe2, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyappClient is the client API for Myapp service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyappClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type myappClient struct {
	cc *grpc.ClientConn
}

func NewMyappClient(cc *grpc.ClientConn) MyappClient {
	return &myappClient{cc}
}

func (c *myappClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.Myapp/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyappServer is the server API for Myapp service.
type MyappServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterMyappServer(s *grpc.Server, srv MyappServer) {
	s.RegisterService(&_Myapp_serviceDesc, srv)
}

func _Myapp_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyappServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Myapp/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyappServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Myapp_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Myapp",
	HandlerType: (*MyappServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _Myapp_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/has1985/myapp/myapp/pkg/pb/service.proto",
}
